-- CREATE TABLE "posts" (
--     "id" serial primary key,
--     "imageUrl" varchar NOT NULL,
--     "name" varchar NOT NULL,
--     "description" varchar NOT NULL,
--     "date" varchar NOT NULL,
--     "category" int NOT NULL,
--     "categoryName" varchar NOT NULL,
--     "likeCount" int NOT NULL,
--     "liked" bool default false,
--     "text" varchar NOT NULL
-- )