version: "3"

services:
  laniakeaCont:
    image: postgres
    container_name: laniakeaCont
    restart: unless-stopped
    networks:
      - lan
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
  post-api:
    image: server/post-api:latest
    container_name: post-api
    restart: unless-stopped
    networks:
      - lan
    ports:
      - "5000:5000"
    depends_on:
      - laniakeaCont
    environment:
      PG_CONN: postgres://${PG_USER}:${PG_PASSWORD}@laniakeaCont:5432/laniakeadb?sslmode=disable   
      PASSWORD: ${PASSWORD}
      HTTP_ADDR: :5000
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-service
    restart: unless-stopped
    networks:
      - lan
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - post-api
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - lan
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASS}
      GF_AUT_ANONYMOUS_ENABLED: "true"
    volumes:
      - "./conf/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./conf/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
      - "./conf/data/dashboards:/var/lib/grafana/dashboards"
    depends_on:
      - prometheus

networks:
  lan:
    driver: bridge